'use strict';

/* .js files in js/pages/ is autogenerated by react/babel */

/** props:
 *      title:      string
 *      link:       string
 *      badge:      string
 *      selected:   bool
 */
function SidebarSectionItem(props) {
    if (props.selectedItem === props.itemId) {
        props.selected = "true";
    }

    return (
        <li>
            <a href={props.link} class={"d-inline-flex align-items-center rounded" +
                (props.link ? "" : " user-select-none") + (props.selected ? " active" : "")}
                id={props.itemId ? "item-" + props.itemId + "-link" : ""}>
                {props.title}
                {props.badge &&
                    <span class={
                        "badge ct-badge ms-2"}>
                        {props.badge}
                    </span>
                }
            </a>
        </li>
    )
}

/** props:
 *      title:      string
 *      sectionId:  string
 * */
function SidebarSection(props) {
    return (
        <li class="mb-1">
            <button class="btn d-inline-flex align-items-center rounded collapsed disabled"
                data-bs-toggle="collapse" data-bs-target={"#" + props.sectionId + "-collapse"} aria-expanded="true">
                {props.title}
            </button>
            <div class="collapse show" id={props.sectionId + "-collapse"}>
                <ul class="list-unstyled fw-normal pb-1 small">
                    {props.children}
                </ul>
            </div>
        </li>
    )
}

function PageSidebarBase(props) {
    return (
        <React.Fragment>
            <button class="btn bg-light btn-outline-secondary ct-sidebar-toggle ct-navbar-sticky-button d-md-none py-0 px-1 ms-auto order-3 collapsed"
                type="button" data-bs-toggle="collapse" data-bs-target="#ct-sections-nav"
                aria-controls="ct-sections-nav" aria-expanded="false" aria-label="Переключить навигацию по разделам">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="bi bi-expand" fill="currentColor"
                    viewBox="0 0 16 16">
                    <title>Expand</title>
                    <path fill-rule="evenodd"
                        d="M1 8a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 0 1h-13A.5.5 0 0 1 1 8zM7.646.146a.5.5 0 0 1 .708 0l2 2a.5.5 0 0 1-.708.708L8.5 1.707V5.5a.5.5 0 0 1-1 0V1.707L6.354 2.854a.5.5 0 1 1-.708-.708l2-2zM8 10a.5.5 0 0 1 .5.5v3.793l1.146-1.147a.5.5 0 0 1 .708.708l-2 2a.5.5 0 0 1-.708 0l-2-2a.5.5 0 0 1 .708-.708L7.5 14.293V10.5A.5.5 0 0 1 8 10z">
                    </path>
                </svg>

                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="bi bi-collapse"
                    fill="currentColor" viewBox="0 0 16 16">
                    <title>Collapse</title>
                    <path fill-rule="evenodd"
                        d="M1 8a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 0 1h-13A.5.5 0 0 1 1 8zm7-8a.5.5 0 0 1 .5.5v3.793l1.146-1.147a.5.5 0 0 1 .708.708l-2 2a.5.5 0 0 1-.708 0l-2-2a.5.5 0 1 1 .708-.708L7.5 4.293V.5A.5.5 0 0 1 8 0zm-.5 11.707l-1.146 1.147a.5.5 0 0 1-.708-.708l2-2a.5.5 0 0 1 .708 0l2 2a.5.5 0 0 1-.708.708L8.5 11.707V15.5a.5.5 0 0 1-1 0v-3.793z">
                    </path>
                </svg>
                {" "}Меню разделов
            </button>
            <nav class="collapse ct-links " id="ct-sections-nav" aria-label="Навигация по разделам">
                <hr class="d-md-none m-0 mx-2" />
                <ul class="list-unstyled mb-0 py-3 pt-md-1">
                    {props.children}
                </ul>
            </nav>
        </React.Fragment>
    );
}

/** props:
 *      selectedItem:   string
 * */
function PageSidebar(props) {
    return (
        <PageSidebarBase>
            <SidebarSection title="Основы Java" sectionId="java-start">
                <SidebarSectionItem title="Все, что нужно для старта" link="get_started.html" itemId="get-started" selectedItem={props.selectedItem} />
                <SidebarSectionItem title="Базовые понятия" badge="скоро" itemId="base-knowledges" selectedItem={props.selectedItem}/>
            </SidebarSection>
            <SidebarSection title="Задачи" sectionId="tasks">
                <SidebarSectionItem title="Begin" badge="скоро" itemId="begin" selectedItem={props.selectedItem}/>
                <SidebarSectionItem title="Integer" badge="скоро" itemId="integer" selectedItem={props.selectedItem}/>
                <SidebarSectionItem title="Boolean" badge="скоро" itemId="boolean" selectedItem={props.selectedItem}/>
            </SidebarSection>
        </PageSidebarBase>
    )
}

ReactDOM.render(
    <PageSidebar />,
    document.getElementById('page_sidebar_container')
);
