'use strict';

/* .js files in js/pages/ is autogenerated by react/babel */

/** props:
 *      title:      string
 *      link:       string
 *      badge:      string
 *      selected:   bool
 */

function SidebarSectionItem(props) {
    if (props.selectedItem === props.itemId) {
        props.selected = "true";
    }

    return React.createElement(
        "li",
        null,
        React.createElement(
            "a",
            { href: props.link, "class": "d-inline-flex align-items-center rounded" + (props.link ? "" : " user-select-none") + (props.selected ? " active" : ""),
                id: props.itemId ? "item-" + props.itemId + "-link" : "" },
            props.title,
            props.badge && React.createElement(
                "span",
                { "class": "badge ct-badge ms-2" },
                props.badge
            )
        )
    );
}

/** props:
 *      title:      string
 *      sectionId:  string
 * */
function SidebarSection(props) {
    return React.createElement(
        "li",
        { "class": "mb-1" },
        React.createElement(
            "button",
            { "class": "btn d-inline-flex align-items-center rounded collapsed disabled",
                "data-bs-toggle": "collapse", "data-bs-target": "#" + props.sectionId + "-collapse", "aria-expanded": "true" },
            props.title
        ),
        React.createElement(
            "div",
            { "class": "collapse show", id: props.sectionId + "-collapse" },
            React.createElement(
                "ul",
                { "class": "list-unstyled fw-normal pb-1 small" },
                props.children
            )
        )
    );
}

function PageSidebarBase(props) {
    return React.createElement(
        React.Fragment,
        null,
        React.createElement(
            "button",
            { "class": "btn bg-light btn-outline-secondary ct-sidebar-toggle ct-navbar-sticky-button d-md-none py-0 px-1 ms-auto order-3 collapsed",
                type: "button", "data-bs-toggle": "collapse", "data-bs-target": "#ct-sections-nav",
                "aria-controls": "ct-sections-nav", "aria-expanded": "false", "aria-label": "\u041F\u0435\u0440\u0435\u043A\u043B\u044E\u0447\u0438\u0442\u044C \u043D\u0430\u0432\u0438\u0433\u0430\u0446\u0438\u044E \u043F\u043E \u0440\u0430\u0437\u0434\u0435\u043B\u0430\u043C" },
            React.createElement(
                "svg",
                { xmlns: "http://www.w3.org/2000/svg", width: "24", height: "24", "class": "bi bi-expand", fill: "currentColor",
                    viewBox: "0 0 16 16" },
                React.createElement(
                    "title",
                    null,
                    "Expand"
                ),
                React.createElement("path", { "fill-rule": "evenodd",
                    d: "M1 8a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 0 1h-13A.5.5 0 0 1 1 8zM7.646.146a.5.5 0 0 1 .708 0l2 2a.5.5 0 0 1-.708.708L8.5 1.707V5.5a.5.5 0 0 1-1 0V1.707L6.354 2.854a.5.5 0 1 1-.708-.708l2-2zM8 10a.5.5 0 0 1 .5.5v3.793l1.146-1.147a.5.5 0 0 1 .708.708l-2 2a.5.5 0 0 1-.708 0l-2-2a.5.5 0 0 1 .708-.708L7.5 14.293V10.5A.5.5 0 0 1 8 10z" })
            ),
            React.createElement(
                "svg",
                { xmlns: "http://www.w3.org/2000/svg", width: "24", height: "24", "class": "bi bi-collapse",
                    fill: "currentColor", viewBox: "0 0 16 16" },
                React.createElement(
                    "title",
                    null,
                    "Collapse"
                ),
                React.createElement("path", { "fill-rule": "evenodd",
                    d: "M1 8a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 0 1h-13A.5.5 0 0 1 1 8zm7-8a.5.5 0 0 1 .5.5v3.793l1.146-1.147a.5.5 0 0 1 .708.708l-2 2a.5.5 0 0 1-.708 0l-2-2a.5.5 0 1 1 .708-.708L7.5 4.293V.5A.5.5 0 0 1 8 0zm-.5 11.707l-1.146 1.147a.5.5 0 0 1-.708-.708l2-2a.5.5 0 0 1 .708 0l2 2a.5.5 0 0 1-.708.708L8.5 11.707V15.5a.5.5 0 0 1-1 0v-3.793z" })
            ),
            "\u041C\u0435\u043D\u044E \u0440\u0430\u0437\u0434\u0435\u043B\u043E\u0432"
        ),
        React.createElement(
            "nav",
            { "class": "collapse ct-links ", id: "ct-sections-nav", "aria-label": "\u041D\u0430\u0432\u0438\u0433\u0430\u0446\u0438\u044F \u043F\u043E \u0440\u0430\u0437\u0434\u0435\u043B\u0430\u043C" },
            React.createElement("hr", { "class": "d-md-none m-0 mx-2" }),
            React.createElement(
                "ul",
                { "class": "list-unstyled mb-0 py-3 pt-md-1" },
                props.children
            )
        )
    );
}

/** props:
 *      selectedItem:   string
 * */
function PageSidebar(props) {
    return React.createElement(
        PageSidebarBase,
        null,
        React.createElement(
            SidebarSection,
            { title: "\u041E\u0441\u043D\u043E\u0432\u044B Java", sectionId: "java-start" },
            React.createElement(SidebarSectionItem, { title: "\u0412\u0441\u0435, \u0447\u0442\u043E \u043D\u0443\u0436\u043D\u043E \u0434\u043B\u044F \u0441\u0442\u0430\u0440\u0442\u0430", link: "get_started.html", itemId: "get-started", selectedItem: props.selectedItem }),
            React.createElement(SidebarSectionItem, { title: "\u0411\u0430\u0437\u043E\u0432\u044B\u0435 \u043F\u043E\u043D\u044F\u0442\u0438\u044F", badge: "\u0441\u043A\u043E\u0440\u043E", itemId: "base-knowledges", selectedItem: props.selectedItem })
        ),
        React.createElement(
            SidebarSection,
            { title: "\u0417\u0430\u0434\u0430\u0447\u0438", sectionId: "tasks" },
            React.createElement(SidebarSectionItem, { title: "Begin", badge: "\u0441\u043A\u043E\u0440\u043E", itemId: "begin", selectedItem: props.selectedItem }),
            React.createElement(SidebarSectionItem, { title: "Integer", badge: "\u0441\u043A\u043E\u0440\u043E", itemId: "integer", selectedItem: props.selectedItem }),
            React.createElement(SidebarSectionItem, { title: "Boolean", badge: "\u0441\u043A\u043E\u0440\u043E", itemId: "boolean", selectedItem: props.selectedItem })
        )
    );
}