'use strict';

/* .js files in js/pages/ is autogenerated by react/babel */

function PageHeader(props) {
    return React.createElement(
        "header",
        { "class": "navbar navbar-expand-md navbar-light bg-light ct-navbar py-lg-3 px-lg-2" },
        React.createElement(
            "nav",
            { "class": "container-xxl align-items-baseline", "aria-label": "\u041E\u0441\u043D\u043E\u0432\u043D\u0430\u044F \u043D\u0430\u0432\u0438\u0433\u0430\u0446\u0438\u044F" },
            React.createElement(
                "a",
                { href: "index.html", "class": "navbar-brand ct-brand" },
                React.createElement(
                    "span",
                    { "class": "bg-primary text-white px-2 rounded-3" },
                    "Code"
                ),
                " Tasks"
            ),
            React.createElement(
                "button",
                { "class": "navbar-toggler collapsed", type: "button", "data-bs-toggle": "collapse", "data-bs-target": "#ctNavbar",
                    "aria-controls": "ctNavbar", "aria-expanded": "false", "aria-label": "Toggle navigation" },
                React.createElement("span", { "class": "navbar-toggler-icon" })
            ),
            React.createElement(
                "div",
                { "class": "collapse navbar-collapse", id: "ctNavbar" },
                React.createElement(
                    "span",
                    { "class": "navbar-text pe-2" },
                    "\u0418\u0437\u0443\u0447\u0435\u043D\u0438\u0435 \u044F\u0437\u044B\u043A\u043E\u0432 \u043F\u0440\u043E\u0433\u0440\u0430\u043C\u043C\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u044F"
                ),
                React.createElement("hr", { "class": "d-md-none ct-hr" }),
                React.createElement(
                    "ul",
                    { "class": "navbar-nav flex-row flex-wrap ms-md-auto justify-content-end" },
                    React.createElement(
                        "li",
                        { "class": "nav-item col-6 col-md-auto" },
                        React.createElement(
                            "a",
                            { "class": "nav-link p-2 d-inline-flex align-items-center", href: "https://github.com/KostarSf/",
                                target: "_blank", rel: "noopener" },
                            React.createElement(
                                "svg",
                                { xmlns: "http://www.w3.org/2000/svg", width: "36", height: "36",
                                    "class": "navbar-nav-svg d-inline-block align-text-top", viewBox: "0 0 512 499.36",
                                    role: "img" },
                                React.createElement(
                                    "title",
                                    null,
                                    "GitHub"
                                ),
                                React.createElement("path", { fill: "currentColor", "fill-rule": "evenodd",
                                    d: "M256 0C114.64 0 0 114.61 0 256c0 113.09 73.34 209 175.08 242.9 12.8 2.35 17.47-5.56 17.47-12.34 0-6.08-.22-22.18-.35-43.54-71.2 15.49-86.2-34.34-86.2-34.34-11.64-29.57-28.42-37.45-28.42-37.45-23.27-15.84 1.73-15.55 1.73-15.55 25.69 1.81 39.21 26.38 39.21 26.38 22.84 39.12 59.92 27.82 74.5 21.27 2.33-16.54 8.94-27.82 16.25-34.22-56.84-6.43-116.6-28.43-116.6-126.49 0-27.95 10-50.8 26.35-68.69-2.63-6.48-11.42-32.5 2.51-67.75 0 0 21.49-6.88 70.4 26.24a242.65 242.65 0 0 1 128.18 0c48.87-33.13 70.33-26.24 70.33-26.24 14 35.25 5.18 61.27 2.55 67.75 16.41 17.9 26.31 40.75 26.31 68.69 0 98.35-59.85 120-116.88 126.32 9.19 7.9 17.38 23.53 17.38 47.41 0 34.22-.31 61.83-.31 70.23 0 6.85 4.61 14.81 17.6 12.31C438.72 464.97 512 369.08 512 256.02 512 114.62 397.37 0 256 0z" })
                            ),
                            React.createElement(
                                "small",
                                { "class": "d-md-none ms-2" },
                                "GitHub"
                            )
                        )
                    ),
                    React.createElement(
                        "li",
                        { "class": "nav-item col-6 col-md-auto" },
                        React.createElement(
                            "a",
                            { "class": "nav-link p-2 d-inline-flex align-items-center", href: "https://vk.com/shainert",
                                target: "_blank", rel: "noopener" },
                            React.createElement(
                                "svg",
                                { xmlns: "http://www.w3.org/2000/svg", width: "36", height: "36",
                                    "class": "navbar-nav-svg d-inline-block align-text-top", viewBox: "2 2 21 21", role: "img" },
                                React.createElement(
                                    "title",
                                    null,
                                    "VK"
                                ),
                                React.createElement("path", { fill: "currentColor", "fill-rule": "evenodd",
                                    d: "M15.07294,2H8.9375C3.33331,2,2,3.33331,2,8.92706V15.0625C2,20.66663,3.32294,22,8.92706,22H15.0625C20.66669,22,22,20.67706,22,15.07288V8.9375C22,3.33331,20.67706,2,15.07294,2Zm3.07287,14.27081H16.6875c-.55206,0-.71875-.44793-1.70831-1.4375-.86463-.83331-1.22919-.9375-1.44794-.9375-.30206,0-.38544.08332-.38544.5v1.3125c0,.35419-.11456.5625-1.04162.5625a5.69214,5.69214,0,0,1-4.44794-2.66668A11.62611,11.62611,0,0,1,5.35419,8.77081c0-.21875.08331-.41668.5-.41668H7.3125c.375,0,.51044.16668.65625.55212.70831,2.08331,1.91669,3.89581,2.40625,3.89581.1875,0,.27081-.08331.27081-.55206V10.10413c-.0625-.97913-.58331-1.0625-.58331-1.41663a.36008.36008,0,0,1,.375-.33337h2.29169c.3125,0,.41662.15625.41662.53125v2.89587c0,.3125.13544.41663.22919.41663.1875,0,.33331-.10413.67706-.44788a11.99877,11.99877,0,0,0,1.79169-2.97919.62818.62818,0,0,1,.63544-.41668H17.9375c.4375,0,.53125.21875.4375.53125A18.20507,18.20507,0,0,1,16.41669,12.25c-.15625.23956-.21875.36456,0,.64581.14581.21875.65625.64582,1,1.05207a6.48553,6.48553,0,0,1,1.22912,1.70837C18.77081,16.0625,18.5625,16.27081,18.14581,16.27081Z" })
                            ),
                            React.createElement(
                                "small",
                                { "class": "d-md-none ms-2" },
                                "VK"
                            )
                        )
                    )
                ),
                React.createElement(
                    "a",
                    { href: "donation.html", "class": "btn btn-ct-donate d-lg-inline-block my-2 my-md-0 ms-md-3" },
                    "\u041F\u043E\u0434\u0434\u0435\u0440\u0436\u0430\u0442\u044C"
                )
            )
        )
    );
}

ReactDOM.render(React.createElement(PageHeader, null), document.getElementById('page_header_container'));